castai/k8s-agent

- internal/services/controller/controller.go
- internal/services/controller/controller_test.go
- internal/services/providers/eks/eks.go
- internal/services/providers/eks/eks_test.go
- GKE adds labels to the nodes after creation
- This means we should not be using spot cache for GKE, there is no need for that
- The cache was used as a historical reason because on the EKS side, we actually need to execute API call to identify whether some of the nodes are Spot
> fix(isSpot): use spot cache for EKS only

- internal/castai/castai.go
- internal/services/controller/controller.go
- internal/services/controller/controller_exclude_race_test.go
- internal/services/controller/controller_test.go
- internal/services/controller/delta.go
- internal/services/providers/aks/aks.go
- internal/services/providers/aks/aks_test.go
- internal/services/providers/castai/castai.go
- internal/services/providers/eks/eks.go
- internal/services/providers/eks/eks_test.go
- internal/services/providers/gke/gke.go
- internal/services/providers/gke/gke_test.go
- internal/services/providers/kops/kops.go
- internal/services/providers/kops/kops_test.go
- internal/services/providers/providers.go
- internal/services/providers/types/mock/provider.go
- internal/services/providers/types/types.go
Agent will no longer check whether a node is spot in the informer event handler. Instead, it will do that before sending the delta request. This is needed to be able to batch the request, to avoid getting rate limit errors in cloud APIs.
> chore: optimize spot node discovery

- internal/services/providers/eks/client/aws.go
- internal/services/providers/eks/client/mock/client.go
- internal/services/providers/eks/eks.go
- internal/services/providers/eks/eks_test.go
- internal/services/providers/kops/kops.go
- internal/services/providers/kops/kops_test.go
Querying nodes by `kubernetes.io/hostname` label's value is unreliable as it can be duplicated throughout the nodes. Instead, if we query the node by EC2 instance ID, we make sure we get the expected node.
> CO-1540: Query AWS nodes by instanceID

- internal/config/config.go
- internal/services/controller/controller.go
- internal/services/controller/controller_exclude_race_test.go
- internal/services/controller/controller_test.go
- internal/services/controller/healthz.go
- internal/services/controller/healthz_test.go
- internal/services/controller/worker.go
- main.go
Agent will now have a healthz endpoint at `:9876`. It has just these checks:
1. If the controller is unable to properly initialize in by default `15m30s` it will become unhealthy.
2. If the controller does not send snapshot after initializing or time since the last snapshot is by default longer than `10m` it will become unhealthy.
> feat: add healthz endpoint and graceful shutdown

- redhat/Dockerfile
The source image creates certificate errors and is much larger than the non-source image.
> Switch off -source image

- redhat/Dockerfile
Redhat has a certification process, we need our license and userID specified in the docker build. I've added these functions.
> add license and userId to RH container build.

- internal/services/controller/controller.go
- internal/services/controller/controller_test.go
in order to apply the correct access rules, the informer name should be plural
> fix: rename ConfigMap conditional informer

- internal/services/controller/controller.go
- internal/services/controller/controller_test.go
Previously, we sent cluster deltas using a non-sliding interval. The order was like this:
- wait for the time to send
- start sending
- finish sending
- start counting towards the next time to send.
This means that long sends will delay sending the next delta. And if sending the delta is delayed, so is the next autoscaling cycle.
In this commit we move to sending cluster deltas using a non-sliding window.
> feat: send cluster deltas with a non-sliding interval

- cmd/agent/run.go
- cmd/dump/run.go
- cmd/monitor/run.go
- internal/castai/castai.go
- internal/config/config.go
- internal/config/version.go
- internal/services/controller/controller.go
- main.go
Some other changes:
- refactor agentVersion to set it as global var in config.go
- print requestID header on HTTP failures
- use proper User-Agent header
> feat: More http client configuration options

- internal/services/controller/controller_test.go
I wanted to refactor this test outside my primary task in order to isolate changes and avoid huge diffs. I want this test to:
- easily accept samples having the same kind but different GV (currently, we don't have such sample as we don't support them yet)
- support using `unstructured.Unstructured` runtime type (which is why data is compared using JSON helpers rather than plain bytes).
Also, note:
- To maintain consistency, updated other test cases to use the same pattern to compare the serialised JSONs.
- Added `TypeMeta` values everywhere to be more consistent as we start caring about these for some types.
> chore: refactor controller_test

- internal/services/controller/controller.go
- internal/services/controller/delta/delta.go
This is only possible given the limited scope of the change. However, we decided it might be worth implementing and pushing this to test the new behaviour before updating all agents to it. This change intentionally duplicates code with the idea being that this should make it easier to just drop one of the two implementations with little effort.
> feat: implement double delta calculation to compare two implementations

- internal/services/controller/controller.go
- internal/services/controller/delta/delta.go
Couldn't observe any errors with this in almost a week. While there is a limited expose (slow version rollout), I think this should be enough to merge this change and continue using the TypeMeta information for the cache key (deduplication) and Kind value.
Overall, this is part of the move to use generic `Unstructured` runtime type for some of the objects collected.
> feat: TypeMeta as primary object Kind value source

- internal/services/controller/controller.go
- internal/services/controller/controller_test.go
This test was missing. While it doesn't cover everything related, this verifies at least some informer basics.
> chore: Add unit test for PodMetrics object informer

- cmd/agent/run.go
- internal/config/config.go
- internal/config/config_test.go
- Add some logs around HTTP servers as we currently have the issue when healthz server is not able to reply on any requests 
- Add direct checking if required port for HTTP server is free
- Changed error handling for errors from `ListenAndServe()`,  inspiration form https://dev.to/mokiat/proper-http-shutdown-in-go-3fji, `http.ErrServerClosed` is the special error, it shouldn't be handled as other errors because then we're getting misleading error message `time="2024-09-25T18:24:46Z" level=error msg="agent stopped with an error: healthz server: http: Server closed" version=v0.64.0` - this shows that agent was closed because server was closed, but in real scenario server was closed because container was killed by Kubernetes
- Fix setting port for pprof server
Example new logs:
``` …
```
> Improve logging for servers and fix setting pprof port

- internal/services/controller/controller.go
- internal/services/controller/controller_test.go
- internal/services/controller/knowngv/constants.go
Karpenter V1 objects have the same naming and very similar structure to the v1beta1 objects. Since we are using unstructured type, it should just proxy these without any structure validation.
> feat: Collect Karpenter v1 objects

- cmd/agent/run.go
- cmd/monitor/run.go
- pkg/log/exporter.go
for details please see comments in the code
example logs without changes from this pull request when `provider` env was set to wrong value:
```
time="2025-01-02T15:06:02Z" level=info msg="closing healthz server" component_node_name=ip-192-168-48-224.eu-central-1.compute.internal component_pod_name=castai-agent-749d64cb88-6d2tr version=v0.76.0
time="2025-01-02T15:06:02Z" level=warning msg="healthz server closed" component_node_name=ip-192-168-48-224.eu-central-1.compute.internal component_pod_name=castai-agent-749d64cb88-6d2tr version=v0.76.0
time="2025-01-02T15:06:02Z" level=info msg="closing pprof server" component_node_name=ip-192-168-48-224.eu-central-1.compute.internal component_pod_name=castai-agent-749d64cb88-6d2tr version=v0.76.0
time="2025-01-02T15:06:02Z" level=warning msg="pprof …
```
> Improve logging and set exit code according to the exit status

- internal/castai/castai.go
`func ExponentialBackoffWithContext(ctx context.Context, backoff Backoff, condition ConditionWithContextFunc) error` repeats a condition check with exponential backoff. It immediately returns an error if the condition returns an error, the context is cancelled or hits the deadline,
or if the maximum attempts defined in backoff is exceeded (ErrWaitTimeout).
Agent logs without this change (only one attempt):
```
time="2025-01-16T15:58:27Z" level=warning msg="failed sending delta request: Post \"https://api--mac-2.local.cast.ai/v1/kubernetes/clusters/36b93485-f902-41a7-a8bc-cb7494d1c56b/agent-deltas\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" attempts=1 cluster_id=36b93485-f902-41a7-a8bc-cb7494d1c56b …
```
> Don't return error when attempt of sending delta fails to allow next attempt

- internal/services/controller/controller_test.go
- internal/services/controller/crd/types.go
**Description**
- Update the Recommendation CR struct to include the new status field.
```yaml
apiVersion: autoscaling.cast.ai/v1
kind: Recommendation
metadata:
generation: 1
name: conditional-exit-deployment-deployment
namespace: default
spec:
recommendation:
- containerName: conditional-container
requests:
cpu: 10m
memory: 10Mi
targetRef:
kind: Deployment
name: conditional-exit-deployment
status:
conditions:
- lastTransitionTime: "2025-01-29T14:23:46Z"
message: 'The recommendation wasn''t applied immediately as it would create
a new ReplicaSet. Multiple old ReplicaSets exceeding the history limit suggest
possible misconfiguration—please review your settings (max allowed: 12, got:
13).'
observedGeneration: 1
reason: SafeguardTriggered
status: "False"
type: Healthy
```
> Update status for Recommendation CR

- internal/services/controller/informers/podmetrics.go
We were using a buffered channel to signal the "Stop" action, but we were reading the channel at two places, so we would end up consuming the message inside the `for metrics` loop, and the `backoff.BackoffUntil` wouldn't stop.
We're fixing this by actually closing the channel instead of sending a message. Closed channels always returns `nil` on recv immediately.
> fix: Eliminate a race condition in podmetrics informer

- internal/services/controller/delta/delta.go
When using `RLock` for write operations, we allow for race conditions which might mess up the entire map or lose data (i.e. when the map gets expanded).
> fix: acquire explicit lock when saving delta events to map

- .github/workflows/golangci-lint.yaml
- .golangci.yml
Ran `golangci-lint migrate` in this repository. The older version doesn't work with the linter version I have locally (no longer supported). Nobody complained so either nobody is running it or they are using older linters.
GitHub action also had to be upgraded (to support newer config file) so I picked latest (`v7`). Probably doesn't matter too much.
> chore: golangci-lint migrate

- .github/workflows/build.yaml
- .github/workflows/golangci-lint.yaml
- go.mod
- go.sum
No particular reason, just upgrading Go version.
> chore: Use Go v1.24.2
